# Generated by Django 2.0.7 on 2018-07-22 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agresor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('nacionalidad', models.CharField(max_length=30)),
                ('ocupacion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Femicidio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=10)),
                ('circunstancia', models.CharField(max_length=40)),
                ('tipo_arma', models.CharField(max_length=30)),
                ('testigo', models.CharField(max_length=30)),
                ('agresor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Agresor')),
            ],
        ),
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('tiempo', models.CharField(max_length=30)),
                ('agresion_previa', models.CharField(max_length=30)),
                ('agresor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Agresor')),
            ],
        ),
        migrations.CreateModel(
            name='Victima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('nacionalidad', models.CharField(max_length=30)),
                ('ocupacion', models.CharField(max_length=30)),
                ('causa', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='relacion',
            name='victima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Victima'),
        ),
        migrations.AddField(
            model_name='femicidio',
            name='victima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Victima'),
        ),
    ]
