# Generated by Django 2.0.7 on 2018-07-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='femicidio',
            name='fecha',
            field=models.CharField(max_length=10),
        ),
    ]
